### ISSUE TITLE
Error when upgrading antergos-repo-priority

### ISSUE THREAD

**Issue by Swipe650** [Antergos/antergos-packages#108]
[2016-06-12 13:42] [ALPM] installed antergos-repo-priority (1.0.4-2)
[2016-06-12 13:42] [ALPM-SCRIPTLET] Traceback (most recent call last):
[2016-06-12 13:42] [ALPM-SCRIPTLET]   File "/usr/bin/antergos-repo-priority.py", line 132, in <module>
[2016-06-12 13:42] [ALPM-SCRIPTLET]     setup_gettext()
[2016-06-12 13:42] [ALPM-SCRIPTLET]   File "/usr/bin/antergos-repo-priority.py", line 38, in setup_gettext
[2016-06-12 13:42] [ALPM-SCRIPTLET]     lang = gettext.translation(APP_NAME, LOCALE_DIR, [locale_code], None, True)
[2016-06-12 13:42] [ALPM-SCRIPTLET]   File "/usr/lib/python3.5/gettext.py", line 413, in translation
[2016-06-12 13:42] [ALPM-SCRIPTLET]     mofiles = find(domain, localedir, languages, all=True)
[2016-06-12 13:42] [ALPM-SCRIPTLET]   File "/usr/lib/python3.5/gettext.py", line 385, in find
[2016-06-12 13:42] [ALPM-SCRIPTLET]     for nelang in _expand_lang(lang):
[2016-06-12 13:42] [ALPM-SCRIPTLET]   File "/usr/lib/python3.5/gettext.py", line 114, in _expand_lang
[2016-06-12 13:42] [ALPM-SCRIPTLET]     loc = locale.normalize(loc)
[2016-06-12 13:42] [ALPM-SCRIPTLET]   File "/usr/lib/python3.5/locale.py", line 393, in normalize
[2016-06-12 13:42] [ALPM-SCRIPTLET]     code = localename.lower()
[2016-06-12 13:42] [ALPM-SCRIPTLET] AttributeError: 'NoneType' object has no attribute 'lower'
[2016-06-12 13:42] [ALPM] upgraded antergos-mirrorlist (20160125-1 -> 20160611-1)

**Comment by lots0logs** [comment]
Issue moved to [Antergos/antergos-repo-priority #4](https://github.com/Antergos/antergos-repo-priority/issues/4) via [**ZenHub.io**](https://www.zenhub.io/)
