### ISSUE TITLE
pacstrap /mnt antergos-base fails

### ISSUE THREAD

**Issue by fourstone** [Antergos/antergos-packages#151]
# Motivation:
I had the need to install Antergos manually as I had set my Mind on getting Antergos setup on an encrypted RAID1 ZFS.. (just as background)

I am used to installing archlinux using pacstrap and doing may things myself so I decided to do the same with antergos as it has ZFS builtin.

# error description:
0: boot with Antergos install DVD in textmode
1: prepare a /mnt partition like described in the archlinux installation guide
2a: pacstrap /mnt base works
2b: pacstrap /mnt antergos-base works except the 3 antergos packages

2z: workaround: pacstrap /mnt base, then copy the antergos mirror information into target system, update the pacman.conf to include antergos, then chroot into system, do pacman -S antergos-base and everything works fine.

# probably these packages are just not able to be pacstrapped. Is that by intention?

kind regards, martin

**Comment by karasu** [comment]
Hi,

Yes, Antergos is not ready to be installed this way "automagically". Your "workaround" is the only way as it is now.

Which were the three packages that pacstrap was unable to install? Dependency problems?

**Comment by fourstone** [comment]
The 3 packages are 
antergos-keyring
antergos-mirrorlist
antergos-repo-priority

(basically all the difference between base and antergos-base)

Just wondering how much effort it would be to enable these three packages to be pacstrapped. In the meantime it might be good to have some small not telling you this detail somewhere on the antergos page (could not find it anywhere)

**Comment by fourstone** [comment]
log:
```
pacstrap /mnt antergos-base
...
(79/83) installing gdk-pixbuf2                                                                                            [#########################################################################] 100%
(80/83) installing libnotify                                                                                              [#########################################################################] 100%
(81/83) installing gettext                                                                                                [#########################################################################] 100%
Optional dependencies for gettext
    git: for autopoint infrastructure updates
(82/83) installing antergos-repo-priority                                                                                 [#########################################################################] 100%
ln: failed to create symbolic link '/usr/share/antergos/logo-square32.png': No such file or directory
Traceback (most recent call last):
  File "/usr/bin/antergos-repo-priority.py", line 132, in <module>
    setup_gettext()
  File "/usr/bin/antergos-repo-priority.py", line 38, in setup_gettext
    lang = gettext.translation(APP_NAME, LOCALE_DIR, [locale_code], None, True)
  File "/usr/lib/python3.6/gettext.py", line 505, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib/python3.6/gettext.py", line 477, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python3.6/gettext.py", line 206, in _expand_lang
    loc = locale.normalize(loc)
  File "/usr/lib/python3.6/locale.py", line 396, in normalize
    code = localename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
/usr/bin/antergos-notify.sh: line 56: ps: command not found
/usr/bin/antergos-notify.sh: line 56: awk: command not found
/usr/bin/antergos-notify.sh: line 56: grep: command not found
/usr/bin/antergos-notify.sh: line 57: ps: command not found
/usr/bin/antergos-notify.sh: line 57: awk: command not found
/usr/bin/antergos-notify.sh: line 57: grep: command not found
(83/83) installing antergos-mirrorlist                                                                                    [#########################################################################] 100%
:: Running post-transaction hooks...
(1/4) Checking antergos repo priority.
Traceback (most recent call last):
  File "/usr/bin/antergos-repo-priority.py", line 132, in <module>
    setup_gettext()
  File "/usr/bin/antergos-repo-priority.py", line 38, in setup_gettext
    lang = gettext.translation(APP_NAME, LOCALE_DIR, [locale_code], None, True)
  File "/usr/lib/python3.6/gettext.py", line 505, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib/python3.6/gettext.py", line 477, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python3.6/gettext.py", line 206, in _expand_lang
    loc = locale.normalize(loc)
  File "/usr/lib/python3.6/locale.py", line 396, in normalize
    code = localename.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
error: command failed to execute correctly
(2/4) Probing GDK-Pixbuf loader modules...
(3/4) Rebuilding certificate stores...
(4/4) Updating the MIME type database...
```

**Comment by karasu** [comment]
I see...  antergos-repo-priority uses python in its post install hook. That's a no no if you want to pacstrap it. I'll talk with its packager (lots0logs), but I think we should leave this package out of antergos-base (as if the user wants to install using pacstrap, I think it's his/her responsability to add the antergos repository to pacman.conf).

Thanks for the info!
