### ISSUE TITLE
GitKraken not starting

### ISSUE THREAD

**Issue by RafoxSama** [Antergos/antergos-packages#167]
➜  ~ gitkraken
Node started time: 1487397486273
/usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /opt/gitkraken/resources/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node)
Error: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /opt/gitkraken/resources/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node)
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/v1_5_0.js:7:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/index.js:5:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/gitkraken/resources/app.asar/src/appBootstrap/upgradeScripts/index.js:7:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at EventEmitter.module.exports.app.on (/opt/gitkraken/resources/app.asar/src/appBootstrap/main.js:146:5)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)

**Comment by vuhung3990** [comment]
`sudo apt install libcurl3` gitkraken work again on linux mint

**Comment by nguyenhuutho** [comment]
A Hùng Bá vãi, đúng thật chứ, pro thậtật

**Comment by syarifuddinahmads** [comment]
@vuhung3990  thanks , works for me

**Comment by kcee403** [comment]
"Sorcery!" - Phil Dunphy
