### ISSUE TITLE
Antergos-alerts error

### ISSUE THREAD

**Issue by Swipe650** [Antergos/antergos-packages#215]
```
[2017-06-26 07:14] [ALPM] running 'antergos-alerts.hook'...
[2017-06-26 07:14] [ALPM-SCRIPTLET] Traceback (most recent call last):
[2017-06-26 07:14] [ALPM-SCRIPTLET]   File "/usr/bin/antergos-alerts", line 144, in <module>
[2017-06-26 07:14] [ALPM-SCRIPTLET]     do_alerts()
[2017-06-26 07:14] [ALPM-SCRIPTLET]   File "/usr/bin/antergos-alerts", line 117, in do_alerts
[2017-06-26 07:14] [ALPM-SCRIPTLET]     subject, part1, part2, part3 = get_localized_alert_message()
[2017-06-26 07:14] [ALPM-SCRIPTLET]   File "/usr/bin/antergos-alerts", line 76, in get_localized_alert_message
[2017-06-26 07:14] [ALPM-SCRIPTLET]     subject = _('ATTENTION: Antergos System Message')
[2017-06-26 07:14] [ALPM-SCRIPTLET] NameError: name '_' is not defined
```

**Comment by lots0logs** [comment]
Issue moved to [Antergos/antergos-alerts #2](https://github.com/Antergos/antergos-alerts/issues/2) via [**ZenHub**](https://www.zenhub.com/)
