### ISSUE TITLE
antergos-alerts upgrade error

### ISSUE THREAD

**Issue by Swipe650** [Antergos/antergos-packages#219]
:: Running post-transaction hooks...

Checking for new antergos alerts.
Traceback (most recent call last):
File "/usr/bin/antergos-alerts", line 144, in 
do_alerts()
File "/usr/bin/antergos-alerts", line 117, in do_alerts
subject, part1, part2, part3 = get_localized_alert_message()
File "/usr/bin/antergos-alerts", line 76, in get_localized_alert_message
subject = _('ATTENTION: Antergos System Message')
NameError: name '_' is not defined 
error: command failed to execute correctly

**Comment by lots0logs** [comment]
Issue moved to [Antergos/antergos-alerts #3](https://github.com/Antergos/antergos-alerts/issues/3) via [**ZenHub**](https://www.zenhub.com/)
