### ISSUE TITLE
Vivaldi 1.12 is out please update!

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#239]
https://update.vivaldi.com/update/1.0/relnotes/1.12.955.36.html

as last times i will try to build at home also ;)

**Comment by killajoe** [comment]
The PKGBUILD is getting complicated for me... also i can not find the right chromium source, because chromium in ArchRepo is outdated and vivaldi PKGBUILD from AUR is using chrome now...

**Comment by killajoe** [comment]
i just find it in the release notes: Updated Chromium to 61.0.3163.91

**Comment by killajoe** [comment]
Why is this package soooo complicated

**Comment by killajoe** [comment]
Thanks alot!

**Comment by killajoe** [comment]
`ninja: build stopped: subcommand failed.
Command '['ninja', '-C', '/home/killajoe/Projects/vivaldi/src/chromium-61.0.3163.91/out/Release', '-v', 'gn']' returned non-zero exit status 1
==> FEHLER: Ein Fehler geschah in build().
`

**Comment by killajoe** [comment]
```
Traceback (most recent call last):
  File "../../third_party/yasm/run_yasm.py", line 34, in <module>
    result_code = subprocess.call(sys.argv[1:])
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
https://ptpb.pw/8ufb
