### ISSUE TITLE
scudcloud 1.65 depends on qt5-webkit

### ISSUE THREAD

**Issue by kojole** [Antergos/antergos-packages#291]
`scudcloud` doesn't start because it depends on `qt5-webit`.

```
$ scudcloud
Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 11, in <module>
    load_entry_point('scudcloud==1.65', 'gui_scripts', 'scudcloud')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/scudcloud/__main__.py", line 16, in <module>
    import scudcloud.scudcloud as sca
  File "/usr/lib/python3.6/site-packages/scudcloud/scudcloud.py", line 2, in <module>
    from scudcloud.leftpane import LeftPane
  File "/usr/lib/python3.6/site-packages/scudcloud/leftpane.py", line 5, in <module>
    from PyQt5.QtWebKit import QWebSettings
ImportError: libQt5WebKit.so.5: cannot open shared object file: No such file or directory
```

**Comment by killajoe** [comment]
Both not from Antergos Repository, and scudcloud is a PKGBUILD from AUR as I can see.

**Comment by killajoe** [comment]
We can go into your issue if you ask on Antergos Forum, as this is the wrong place here.

**Comment by killajoe** [comment]
https://build.antergos.com/package/scudcloud ;)
Sorry i do not see this!
So dependencies needs to be updated, as i can see on AUR: https://aur.archlinux.org/packages/scudcloud/
it is depending on qt5-webkit.
As a workaround install from AUR by using yaourt: ``

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/a138701b1f4cdeff399db4cace56d5048421d21a
