### ISSUE TITLE
ruby-sass broken

### ISSUE THREAD

**Issue by c-h-a-r-l-e-s** [Antergos/antergos-packages#293]
It appears that the default ruby-sass package is currently broken. After installing the current version of Antergos and all updates with the Gnome desktop, typing 'sass' at the command prompt results in:

Traceback (most recent call last):
	2: from /usr/bin/sass:22:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem sass (>= 0.a) with executable sass (Gem::GemNotFoundException)

**Comment by c-h-a-r-l-e-s** [comment]
Doing a little more digging, there seems to be both ruby 2.4.0 and ruby 2.5.0 installed by default, with the sass gem in the 2.4.0 gem directory, but the default ruby is 2.5.0? Not sure if that's the issue.

**Comment by c-h-a-r-l-e-s** [comment]
Looking at line 19 of the PKGBUILD:

`local _gemdir="$(ruby -rubygems -e"puts Gem.default_dir")"
`
This seems to be the problem. Running the following command:

`local _gemdir="$(ruby -rubygems -e"puts Gem.default_dir")"
`
Results in:

Traceback (most recent call last):
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ubygems (LoadError)

But, running the following command produces the desired result (I think):

`ruby -e"puts Gem.default_dir"
`
Result:

`/usr/lib/ruby/gems/2.5.0
`
Therefore, I think line 19 should probably be changed to:

`local _gemdir="$(ruby -e"puts Gem.default_dir")"
`

**Comment by c-h-a-r-l-e-s** [comment]
Looks like the dependencies for this build might also need to include 'rdoc'.
