### ISSUE TITLE
Aurman is out of date

### ISSUE THREAD

**Issue by rplanchuelo** [Antergos/antergos-packages#367]
Aurman is out of date. 
The last version is 2.17.1-1 in AUR and Antergos has 2.16.10-1

In addition, Antergos' version is broken:
• [18:02:15] ~ » aurman -Syyu
Traceback (most recent call last):
  File "/usr/bin/aurman", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aurman==2.16.10' distribution was not found and is required by the application

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/bd273a5a330448defaef30886d97d209803342d3

Thanks!
