### ISSUE TITLE
antergos-desktop-settings not downloadable

### ISSUE THREAD

**Issue by Quarkschleuder** [Antergos/antergos-packages#395]
when trying to install with the 2018-10 full iso with recommended cnchi mirror settings:

> [... ]
2018-10-30 05:58:49 [WARNING] SHA256 hash of file antergos-desktop-settings-1.14-1-any.pkg.tar.xz does not match!  (download_hash.py:49)
2018-10-30 05:58:49 [DEBUG  ] Can't download https://mirrors.tuna.tsinghua.edu.cn/antergos/antergos/x86_64/antergos-desktop-settings-1.14-1-any.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2018-10-30 05:59:09 [ERROR  ] Can't download antergos-desktop-settings-1.14-1-any.pkg.tar.xz, even after trying all available mirrors  (download_requests.py:185)
2018-10-30 05:59:09 [ERROR  ] "Can't download needed packages. Cnchi can't continue."  (process.py:185)
2018-10-30 05:59:09 [ERROR  ] Traceback (most recent call last):  (process.py:190)
2018-10-30 05:59:09 [ERROR  ]   File "/usr/share/cnchi/src/installation/process.py", line 167, in run
    self.pkg.packages, self.down.metalinks)  (process.py:190)
2018-10-30 05:59:09 [ERROR  ]   File "/usr/share/cnchi/src/pages/automatic.py", line 281, in run_install
    self.installation.run()  (process.py:190)
2018-10-30 05:59:09 [ERROR  ]   File "/usr/share/cnchi/src/misc/extra.py", line 194, in helper
    return func(*args, **kwargs)  (process.py:190)
2018-10-30 05:59:09 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 296, in run
    self.download_packages()  (process.py:190)
2018-10-30 05:59:09 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 356, in download_packages
    download_packages.start_download(self.metalinks)  (process.py:190)
2018-10-30 05:59:09 [ERROR  ]   File "/usr/share/cnchi/src/download/download.py", line 114, in start_download
    raise misc.InstallError(txt)  (process.py:190)
2018-10-30 05:59:09 [ERROR  ] misc.extra.InstallError: "Can't download needed packages. Cnchi can't continue."  (process.py:190)

**Comment by killajoe** [comment]
@karasu is pushing a new version, but caused by buildserver problem it needs more time to get to the mirrors...

**Comment by Quarkschleuder** [comment]
fixed by devs
