### ISSUE TITLE
update vivaldi to new version

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-packages#412]
`gen.py: error: no such option: --no-sysroot
Traceback (most recent call last):
  File "tools/gn/bootstrap/bootstrap.py", line 96, in <module>
    sys.exit(main(sys.argv[1:]))
  File "tools/gn/bootstrap/bootstrap.py", line 78, in main
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python2', '/home/joekamprad/Dokumente/GitHub/antergos-packages/antergos/vivaldi/src/chromium-70.0.3538.110/tools/gn/build/gen.py', '--no-last-commit-position', '--out-path=/home/joekamprad/Dokumente/GitHub/antergos-packages/antergos/vivaldi/src/chromium-70.0.3538.110/out/Release/gn_build', '--no-sysroot']' returned non-zero exit status 2
`
is what i get on try building with vivaldi 2.1.1337.51 and chromium 70.0.3538.110

**Comment by killajoe** [comment]
As build working with prior version of chrmium source... closing for now ;)
