### ISSUE TITLE
Incorrect SHA256 hash for spl-utils-0.7.13-2. Impacting ability to install to zfs.

### ISSUE THREAD

**Issue by UNIcodeX** [Antergos/antergos-packages#454]
chchi.log 

```
2019-03-28 17:05:30 [DEBUG  ] Looking for spl-utils-0.7.13-2 in 4 mirrors...  (download_requests.py:212)
2019-03-28 17:05:30 [DEBUG  ] Starting new HTTPS connection (1): glua.ua.pt:443  (connectionpool.py:813)
2019-03-28 17:05:30 [INFO   ] Fetching lsb-release 1.4-15 (597/1059)...  (slides.py:240)
2019-03-28 17:05:30 [INFO   ] Fetching spl-utils 0.7.13-2 (598/1059)...  (slides.py:240)
2019-03-28 17:05:46 [DEBUG  ] https://glua.ua.pt:443 "GET /pub/antergos/antergos/x86_64/spl-utils-0.7.13-2-x86_64.pkg.tar.xz HTTP/1.1" 200 17088  (connectionpool.py:393)
2019-03-28 17:05:46 [WARNING] SHA256 hash of file spl-utils-0.7.13-2-x86_64.pkg.tar.xz does not match!  (download_hash.py:49)
2019-03-28 17:05:46 [DEBUG  ] Can't download https://glua.ua.pt/pub/antergos/antergos/x86_64/spl-utils-0.7.13-2-x86_64.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2019-03-28 17:06:06 [DEBUG  ] Starting new HTTPS connection (1): ftp.cc.uoc.gr:443  (connectionpool.py:813)
2019-03-28 17:06:07 [DEBUG  ] https://ftp.cc.uoc.gr:443 "GET /mirrors/linux/antergos/antergos/x86_64/spl-utils-0.7.13-2-x86_64.pkg.tar.xz HTTP/1.1" 200 17088  (connectionpool.py:393)
2019-03-28 17:06:07 [WARNING] SHA256 hash of file spl-utils-0.7.13-2-x86_64.pkg.tar.xz does not match!  (download_hash.py:49)
2019-03-28 17:06:07 [DEBUG  ] Can't download https://ftp.cc.uoc.gr/mirrors/linux/antergos/antergos/x86_64/spl-utils-0.7.13-2-x86_64.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2019-03-28 17:06:27 [DEBUG  ] Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443  (connectionpool.py:813)
2019-03-28 17:06:29 [DEBUG  ] https://mirrors.tuna.tsinghua.edu.cn:443 "GET /antergos/antergos/x86_64/spl-utils-0.7.13-2-x86_64.pkg.tar.xz HTTP/1.1" 200 17088  (connectionpool.py:393)
2019-03-28 17:06:29 [WARNING] SHA256 hash of file spl-utils-0.7.13-2-x86_64.pkg.tar.xz does not match!  (download_hash.py:49)
2019-03-28 17:06:29 [DEBUG  ] Can't download https://mirrors.tuna.tsinghua.edu.cn/antergos/antergos/x86_64/spl-utils-0.7.13-2-x86_64.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2019-03-28 17:06:49 [DEBUG  ] Starting new HTTPS connection (1): mirrors.nic.cz:443  (connectionpool.py:813)
2019-03-28 17:06:52 [DEBUG  ] https://mirrors.nic.cz:443 "GET /antergos/antergos/x86_64/spl-utils-0.7.13-2-x86_64.pkg.tar.xz HTTP/1.1" 200 17088  (connectionpool.py:393)
2019-03-28 17:06:52 [WARNING] SHA256 hash of file spl-utils-0.7.13-2-x86_64.pkg.tar.xz does not match!  (download_hash.py:49)
2019-03-28 17:06:52 [DEBUG  ] Can't download https://mirrors.nic.cz/antergos/antergos/x86_64/spl-utils-0.7.13-2-x86_64.pkg.tar.xz, Cnchi will try another mirror.  (download_requests.py:238)
2019-03-28 17:07:12 [ERROR  ] Can't download spl-utils-0.7.13-2-x86_64.pkg.tar.xz, even after trying all available mirrors  (download_requests.py:185)
2019-03-28 17:07:12 [ERROR  ] "Can't download needed packages. Cnchi can't continue."  (process.py:185)
2019-03-28 17:07:12 [ERROR  ] Traceback (most recent call last):  (process.py:190)
2019-03-28 17:07:12 [ERROR  ]   File "/usr/share/cnchi/src/installation/process.py", line 167, in run
    self.pkg.packages, self.down.metalinks)  (process.py:190)
2019-03-28 17:07:12 [ERROR  ]   File "/usr/share/cnchi/src/pages/zfs.py", line 594, in run_install
    self.installation.run()  (process.py:190)
2019-03-28 17:07:12 [ERROR  ]   File "/usr/share/cnchi/src/misc/extra.py", line 194, in helper
    return func(*args, **kwargs)  (process.py:190)
2019-03-28 17:07:12 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 296, in run
    self.download_packages()  (process.py:190)
2019-03-28 17:07:12 [ERROR  ]   File "/usr/share/cnchi/src/installation/install.py", line 356, in download_packages
    download_packages.start_download(self.metalinks)  (process.py:190)
2019-03-28 17:07:12 [ERROR  ]   File "/usr/share/cnchi/src/download/download.py", line 114, in start_download
    raise misc.InstallError(txt)  (process.py:190)
2019-03-28 17:07:12 [ERROR  ] misc.extra.InstallError: "Can't download needed packages. Cnchi can't continue."  (process.py:190)
2019-03-28 17:07:12 [DEBUG  ] Starting new HTTP connection (1): build.antergos.com:80  (connectionpool.py:205)
2019-03-28 17:07:12 [DEBUG  ] http://build.antergos.com:80 "GET /hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 301 None  (connectionpool.py:393)
2019-03-28 17:07:12 [DEBUG  ] http://build.antergos.com:80 "GET /api/hook?cnchi=2580656b5c7be34e4144a3129a95e421 HTTP/1.1" 200 None  (connectionpool.py:393)
```

**Comment by karasu** [comment]
https://github.com/Antergos/antergos-packages/commit/1d101255af815b3d5de6478a2d27f2eea4932317

Don't know what's wrong... I just issued a rebuild. Will see.

**Comment by UNIcodeX** [comment]
How long does it take for the mirrors to update. Just tried again and got the same error.

**Comment by kebrx** [comment]
spl-utils has not made its way out of staging, according to build.antergos.com.

Additionally, the `spl` package has the same problem with bad hashes, a rebuild on that one would be appreciated.

**Comment by kebrx** [comment]
Just an update, This is the error I get when I try to install from a freshly built Antergos docker container:

```
[root@9b9052ef2b00 /]# pacman -S zfs
resolving dependencies...
looking for conflicting packages...

Packages (11) dkms-2.5-4  linux-5.0.5.arch1-1  linux-firmware-20190313.efd2c1c-1  linux-headers-5.0.5.arch1-1  lsb-release-1.4-15
              mkinitcpio-25-1  mkinitcpio-busybox-1.30.1-1  spl-0.7.13-2  spl-utils-0.7.13-2  zfs-utils-0.7.13-2  zfs-0.7.13-2

Total Download Size:   175.69 MiB
Total Installed Size:  670.63 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 linux-headers-5.0.5.arch1-1-x86_64                             17.0 MiB  10.6M/s 00:02 [###################################################] 100%
 linux-firmware-20190313.efd2c1c-1-any                          77.3 MiB  27.8M/s 00:03 [###################################################] 100%
 mkinitcpio-busybox-1.30.1-1-x86_64                            252.7 KiB  27.4M/s 00:00 [###################################################] 100%
 mkinitcpio-25-1-any                                            40.0 KiB  19.5M/s 00:00 [###################################################] 100%
 linux-5.0.5.arch1-1-x86_64                                     70.7 MiB  22.6M/s 00:03 [###################################################] 100%
 dkms-2.5-4-any                                                 50.9 KiB  16.6M/s 00:00 [###################################################] 100%
 lsb-release-1.4-15-any                                          7.9 KiB  3.85M/s 00:00 [###################################################] 100%
 spl-utils-0.7.13-2-x86_64                                      16.7 KiB   341K/s 00:00 [###################################################] 100%
 spl-0.7.13-2-x86_64                                           433.2 KiB  1960K/s 00:00 [###################################################] 100%
 zfs-utils-0.7.13-2-x86_64                                       3.7 MiB  17.1M/s 00:00 [###################################################] 100%
 zfs-0.7.13-2-x86_64                                             6.3 MiB  30.0M/s 00:00 [###################################################] 100%
(11/11) checking keys in keyring                                                        [###################################################] 100%
(11/11) checking package integrity                                                      [###################################################] 100%
error: spl-utils: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is invalid
:: File /var/cache/pacman/pkg/spl-utils-0.7.13-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: spl: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is invalid
:: File /var/cache/pacman/pkg/spl-0.7.13-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
```

And with the staging repos enabled:

```
[root@9b9052ef2b00 /]# pacman -S zfs
resolving dependencies...
looking for conflicting packages...

Packages (11) dkms-2.5-4  linux-5.0.5.arch1-1  linux-firmware-20190313.efd2c1c-1  linux-headers-5.0.5.arch1-1  lsb-release-1.4-15
              mkinitcpio-25-1  mkinitcpio-busybox-1.30.1-1  spl-0.7.13-2  spl-utils-0.7.13-3  zfs-utils-0.7.13-2  zfs-0.7.13-2

Total Download Size:   175.69 MiB
Total Installed Size:  670.63 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 linux-headers-5.0.5.arch1-1-x86_64                             17.0 MiB  12.3M/s 00:01 [###################################################] 100%
 linux-firmware-20190313.efd2c1c-1-any                          77.3 MiB  27.4M/s 00:03 [###################################################] 100%
 mkinitcpio-busybox-1.30.1-1-x86_64                            252.7 KiB  22.4M/s 00:00 [###################################################] 100%
 mkinitcpio-25-1-any                                            40.0 KiB  19.5M/s 00:00 [###################################################] 100%
 linux-5.0.5.arch1-1-x86_64                                     70.7 MiB  23.3M/s 00:03 [###################################################] 100%
 dkms-2.5-4-any                                                 50.9 KiB  24.9M/s 00:00 [###################################################] 100%
 lsb-release-1.4-15-any                                          7.9 KiB  7.69M/s 00:00 [###################################################] 100%
 spl-utils-0.7.13-3-x86_64                                      16.7 KiB   348K/s 00:00 [###################################################] 100%
 spl-0.7.13-2-x86_64                                           433.2 KiB  2.07M/s 00:00 [###################################################] 100%
 zfs-utils-0.7.13-2-x86_64                                       3.7 MiB  17.6M/s 00:00 [###################################################] 100%
 zfs-0.7.13-2-x86_64                                             6.3 MiB  26.5M/s 00:00 [###################################################] 100%
(11/11) checking keys in keyring                                                        [###################################################] 100%
(11/11) checking package integrity                                                      [###################################################] 100%
error: spl: signature from "Antergos Build Server (Automated Package Build System) <admin@antergos.org>" is invalid
:: File /var/cache/pacman/pkg/spl-0.7.13-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
```

If we enable staging repos, `spl-utils-0.7.13-3` has a valid signature, but we're still waiting on `spl`.

**Comment by UNIcodeX** [comment]
Very good information. I have a couple questions.

How do you enable staging repos?

Why does it have dkms as a dependency, when the zfs and spl packages don't seem to have anything to do with dkms?

I personally chose dkms packages thinking it would keep my install from breaking ability to access zfs pools. Am I incorrect? Am I missing something?

**Comment by kebrx** [comment]
>How do you enable staging repos?
in pacman.conf:

```
[antergos-staging]
SigLevel = TrustAll
Include = /etc/pacman.d/antergos-mirrorlist
```
Do this in the antergos livecd, then it *should* use those repos to handle the rest.

>I personally chose dkms packages thinking it would keep my install from breaking ability to access zfs pools. Am I incorrect? Am I missing something?

DKMS has nothing to do with this issue.  This issue is about an invalid signature on the packages in the main repo.  

@lots0logs just bumped the package. (thank you, you the best!)  I'm fairly confident this will fix our woes.

I'll be testing as soon as I see the package show up in the staging repo, and I'll report back.

**Comment by kebrx** [comment]
Install succeeded.  I think we can close this issue now.

**Comment by UNIcodeX** [comment]
@kebrx Thanks for the explanation. I did know that the issue was due to a bad signature. 

What I'm also asking, while on the subject of ZFS and SPL, is if it would be better to use the DKMS package (which I think are AUR only) or the official repo package (since it doesn't seem to support DKMS [based on the name anyway]). 

Do you know if not using the DKMS version would increase the likelihood for an update to break ability to access ZFS pools, or is it a non-issue in your opinion? Or do you just mark that package as ignored by pacman?

Thank you for everyone's help in getting this resolved.

**Comment by kebrx** [comment]
I've better success with the official repo packages.  I wouldn't play with it unless  you really know what you're doing (in which case, you probably wouldn't need to ask)

In the future, if something similar happens, the entire transaction won't work unless all the packages are good, so you won't likely have any issues with an update causing an unbootable system.  

That said, I'm working on a solution to provide some peace of mind.  I'm working on some pacman hooks to create snapshots and grub entries for booting old systems with ZFS.  Of course, this requires a different dataset configuration than cnchi provides, but I'll be making PRs for that when it's closer to production readiness.

**Comment by UNIcodeX** [comment]
You're working on implementing FreeBSD style boot environments for Antergos? Nice!!

**Comment by UNIcodeX** [comment]
@kebrx I volunteer to test. That and native ZFS root install encryption are high on my wish list.

**Comment by kebrx** [comment]
I'd be happy to loop you in.  I'll make an announcement and let you know when I have something tangible.  Follow my account and I'll throw up a repo for the hooks when I get to a stage where I'm ready to have others play with it.

As far as the native encryption goes, that's high on my list as well and the good news is that it's made it into 0.8, so we should be seeing it this year.  Development of ZFS is sometimes slow, but better slow than buggy.

**Comment by UNIcodeX** [comment]
Excellent. Followed.

Sounds good. Indeed I agree. No good having something if it doesn't work right.

I'll stay tuned for stuff to test. :)
